### ISSUE TITLE
Please change access rights for localisation

### ISSUE THREAD

**Issue by siebrand** [Wikidata-lib/PropertySuggester#209]
You can remove access for the following users:
- @siebrand
- @Nikerabbit 

Please add access for:
- @translatewiki

**Comment by filbertkm** [comment]
Done. (though we also intend to move property suggester to gerrit (https://phabricator.wikimedia.org/T104309) and think @Ladsgroup is actively working on this now

**Comment by Ladsgroup** [comment]
@filbertkm I was working to get this done but you beat me to it :D 
Regarding moving to gerrit, I'm on it but greg-g told me Chad is the person to do it and it's weekend (and he is not in the hackathon) so we should wait a little.
